plugins {
    id 'com.android.application'
}

android {
    namespace 'app.balyvo.mobile'
    compileSdk 35

    defaultConfig {
        applicationId 'app.balyvo.mobile'
        minSdk 26
        targetSdk 35
        versionCode 7
        versionName '0.4.0-preview'
    }

    signingConfigs {
        release {
            storeFile file(System.getenv('BALYVO_KEYSTORE') ?: 'balyvo-release.keystore')
            storePassword System.getenv('BALYVO_STORE_PASSWORD') ?: 'balyvo-preview'
            keyAlias System.getenv('BALYVO_KEY_ALIAS') ?: 'balyvo'
            keyPassword System.getenv('BALYVO_KEY_PASSWORD') ?: 'balyvo-preview'
            enableV1Signing true
            enableV2Signing true
        }
    }

    buildTypes {
        debug {
            debuggable true
        }
        release {
            debuggable false
            minifyEnabled false
            shrinkResources false
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
