package app.balyvo.mobile;

import android.app.*;
import android.os.*;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.content.*;
import android.text.*;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.text.*;
import java.util.*;

public class MainActivity extends Activity {
  static final int INK=Color.parseColor("#0B1513"), CANVAS=Color.parseColor("#F4F7F5"), WHITE=Color.WHITE,
      GREEN=Color.parseColor("#146B57"), LIME=Color.parseColor("#C8F36D"), MUTED=Color.parseColor("#70807B"),
      BORDER=Color.parseColor("#DDE7E3"), RED=Color.parseColor("#D45A5A");
  SharedPreferences p; FrameLayout body; LinearLayout nav; String tab="home", cat="Todos"; ArrayList<Meal> meals=new ArrayList<>();

  @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(CANVAS);getWindow().setNavigationBarColor(WHITE);getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR);p=getSharedPreferences("balyvo",MODE_PRIVATE);seed();splash();}

  void splash(){FrameLayout f=new FrameLayout(this);f.setBackgroundColor(INK);LinearLayout c=col();c.setGravity(Gravity.CENTER);f.addView(c,new FrameLayout.LayoutParams(-1,-1));TextView mark=txt("B",40,INK,true);mark.setGravity(Gravity.CENTER);mark.setBackground(bg(LIME,30,0,0));c.addView(mark,new LinearLayout.LayoutParams(dp(92),dp(92)));TextView n=txt("Balyvo",34,WHITE,true);LinearLayout.LayoutParams np=wrap();np.topMargin=dp(20);c.addView(n,np);TextView s=txt("SUA COMIDA · SEU CONTROLE · SEU PROGRESSO",10,Color.parseColor("#AFC0BB"),true);s.setLetterSpacing(.14f);LinearLayout.LayoutParams sp=wrap();sp.topMargin=dp(8);c.addView(s,sp);setContentView(f);new Handler(Looper.getMainLooper()).postDelayed(this::shell,1200);}

  void shell(){LinearLayout r=col();r.setBackgroundColor(CANVAS);body=new FrameLayout(this);r.addView(body,new LinearLayout.LayoutParams(-1,0,1));nav=row();nav.setPadding(dp(8),dp(5),dp(8),dp(9));nav.setGravity(Gravity.CENTER);nav.setBackgroundColor(WHITE);r.addView(nav,new LinearLayout.LayoutParams(-1,dp(70)));setContentView(r);show("home");}
  void nav(){nav.removeAllViews();navItem("⌂","Hoje","home");navItem("＋","Pratos","meals");navItem("≡","Diário","diary");navItem("↗","Progresso","progress");}
  void navItem(String i,String l,String k){LinearLayout v=col();v.setGravity(Gravity.CENTER);boolean a=k.equals(tab);v.addView(txt(i,21,a?GREEN:MUTED,true),wrap());v.addView(txt(l,10,a?GREEN:MUTED,true),wrap());v.setOnClickListener(x->show(k));nav.addView(v,new LinearLayout.LayoutParams(0,-1,1));}
  void show(String k){tab=k;nav();body.removeAllViews();body.addView(k.equals("home")?home():k.equals("meals")?mealScreen():k.equals("diary")?diary():progress());}

  View home(){ScrollView s=scroll();LinearLayout q=page();s.addView(q);LinearLayout h=row();h.setGravity(Gravity.CENTER_VERTICAL);TextView logo=txt("B",18,INK,true);logo.setGravity(Gravity.CENTER);logo.setBackground(bg(LIME,17,0,0));h.addView(logo,new LinearLayout.LayoutParams(dp(42),dp(42)));h.addView(new View(this),new LinearLayout.LayoutParams(0,1,1));LinearLayout d=col();d.setGravity(Gravity.RIGHT);d.addView(txt("HOJE",10,GREEN,true),wrap());d.addView(txt(new SimpleDateFormat("EEE, dd MMM",new Locale("pt","BR")).format(new Date()),12,MUTED,false),wrap());h.addView(d,wrap());q.addView(h,match());
    TextView k=txt("CONTROLE DO DIA",10,GREEN,true);k.setLetterSpacing(.16f);LinearLayout.LayoutParams kp=match();kp.topMargin=dp(32);q.addView(k,kp);TextView title=txt("Coma bem.\nContinue evoluindo.",31,INK,true);LinearLayout.LayoutParams tp=match();tp.topMargin=dp(5);q.addView(title,tp);
    int used=todayCalories(), goal=goal();LinearLayout hero=card();LinearLayout.LayoutParams hp=match();hp.topMargin=dp(22);q.addView(hero,hp);hero.addView(txt("CALORIAS",10,MUTED,true),match());LinearLayout nums=row();nums.setGravity(Gravity.BOTTOM);nums.addView(txt(""+used,36,INK,true),wrap());TextView un=txt(" kcal consumidas",12,MUTED,true);LinearLayout.LayoutParams up=wrap();up.bottomMargin=dp(7);nums.addView(un,up);hero.addView(nums,match());ProgressBar bar=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);bar.setMax(Math.max(1,goal));bar.setProgress(Math.min(used,goal));bar.setProgressTintList(android.content.res.ColorStateList.valueOf(GREEN));bar.setProgressBackgroundTintList(android.content.res.ColorStateList.valueOf(Color.parseColor("#E7EEEB")));LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,dp(10));bp.topMargin=dp(15);hero.addView(bar,bp);LinearLayout st=row();LinearLayout.LayoutParams stp=match();stp.topMargin=dp(14);hero.addView(st,stp);st.addView(stat("Meta",goal+" kcal"),new LinearLayout.LayoutParams(0,dp(50),1));st.addView(stat("Restantes",Math.max(0,goal-used)+" kcal"),new LinearLayout.LayoutParams(0,dp(50),1));
    LinearLayout ms=row();LinearLayout.LayoutParams msp=match();msp.topMargin=dp(10);q.addView(ms,msp);ms.addView(metric("⚖",f1(weight())+" kg","Peso atual"),new LinearLayout.LayoutParams(0,dp(116),1));ms.addView(new View(this),new LinearLayout.LayoutParams(dp(10),1));ms.addView(metric("◎",f1(bmi()),"IMC atual"),new LinearLayout.LayoutParams(0,dp(116),1));
    LinearLayout cta=row();cta.setGravity(Gravity.CENTER_VERTICAL);cta.setPadding(dp(18),dp(15),dp(18),dp(15));cta.setBackground(bg(INK,22,0,0));LinearLayout.LayoutParams cp=match();cp.topMargin=dp(17);q.addView(cta,cp);cta.addView(txt("＋",30,LIME,false),wrap());LinearLayout ct=col();LinearLayout.LayoutParams ctp=new LinearLayout.LayoutParams(0,-2,1);ctp.leftMargin=dp(10);cta.addView(ct,ctp);ct.addView(txt("Adicionar refeição",15,WHITE,true),match());ct.addView(txt("Escolha um prato pronto em segundos",11,Color.parseColor("#AFC0BB"),false),match());cta.addView(txt("›",28,WHITE,false),wrap());cta.setOnClickListener(v->show("meals"));
    TextView lt=txt("Últimas refeições",18,INK,true);LinearLayout.LayoutParams ltp=match();ltp.topMargin=dp(27);ltp.bottomMargin=dp(10);q.addView(lt,ltp);entries(q,3);TextView note=txt("Valores calóricos são estimativas de referência. O Balyvo auxilia no acompanhamento e não substitui avaliação médica ou nutricional.",10,MUTED,false);note.setGravity(Gravity.CENTER);LinearLayout.LayoutParams no=match();no.topMargin=dp(22);no.bottomMargin=dp(18);q.addView(note,no);return s;}

  View mealScreen(){LinearLayout root=col();root.setBackgroundColor(CANVAS);LinearLayout top=page();top.setPadding(dp(20),dp(17),dp(20),dp(4));TextView k=txt("PRATOS PRONTOS",10,GREEN,true);k.setLetterSpacing(.16f);top.addView(k,match());TextView t=txt("O que você comeu?",30,INK,true);LinearLayout.LayoutParams tp=match();tp.topMargin=dp(5);top.addView(t,tp);top.addView(txt("Escolha o prato e o tamanho. O Balyvo soma para você.",12,MUTED,false),match());EditText search=new EditText(this);search.setHint("Buscar macarrão, frango, peixe...");search.setSingleLine();search.setTextColor(INK);search.setHintTextColor(MUTED);search.setTextSize(14);search.setPadding(dp(15),dp(10),dp(15),dp(10));search.setBackground(bg(WHITE,17,BORDER,1));LinearLayout.LayoutParams sep=match();sep.topMargin=dp(15);top.addView(search,sep);root.addView(top,match());
    HorizontalScrollView hs=new HorizontalScrollView(this);hs.setHorizontalScrollBarEnabled(false);LinearLayout ch=row();ch.setPadding(dp(20),dp(7),dp(20),dp(7));hs.addView(ch,wrap());String[] cats={"Todos","Brasileiro","Massas","Ovos","Carnes","Frango","Peixes","Frutos do mar","Churrasco"};for(String c:cats){TextView z=txt(c,11,c.equals(cat)?WHITE:INK,true);z.setGravity(Gravity.CENTER);z.setPadding(dp(14),dp(9),dp(14),dp(9));z.setBackground(bg(c.equals(cat)?INK:WHITE,99,c.equals(cat)?INK:BORDER,1));LinearLayout.LayoutParams zp=wrap();zp.rightMargin=dp(8);ch.addView(z,zp);z.setOnClickListener(v->{cat=((TextView)v).getText().toString();show("meals");});}root.addView(hs,new LinearLayout.LayoutParams(-1,dp(57)));
    ScrollView sc=scroll();LinearLayout list=col();list.setPadding(dp(20),dp(3),dp(20),dp(25));sc.addView(list);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));Runnable r=()->renderMeals(list,search.getText().toString());search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int b,int c){}public void onTextChanged(CharSequence s,int a,int b,int c){r.run();}public void afterTextChanged(Editable e){}});renderMeals(list,"");return root;}
  void renderMeals(LinearLayout list,String query){list.removeAllViews();String x=query.toLowerCase(Locale.ROOT).trim();int n=0;for(Meal m:meals){if(!cat.equals("Todos")&&!cat.equals(m.c))continue;if(!x.isEmpty()&&!m.n.toLowerCase(Locale.ROOT).contains(x))continue;n++;LinearLayout v=row();v.setGravity(Gravity.CENTER_VERTICAL);v.setPadding(dp(14),dp(13),dp(14),dp(13));v.setBackground(bg(WHITE,19,BORDER,1));TextView em=txt(m.e,27,INK,false);em.setGravity(Gravity.CENTER);em.setBackground(bg(Color.parseColor("#EEF4F1"),15,0,0));v.addView(em,new LinearLayout.LayoutParams(dp(54),dp(54)));LinearLayout inf=col();LinearLayout.LayoutParams ip=new LinearLayout.LayoutParams(0,-2,1);ip.leftMargin=dp(12);v.addView(inf,ip);inf.addView(txt(m.n,14,INK,true),match());inf.addView(txt(m.d,10,MUTED,false),match());LinearLayout kc=col();kc.setGravity(Gravity.RIGHT);kc.addView(txt(""+m.k,17,GREEN,true),wrap());kc.addView(txt("kcal",10,MUTED,true),wrap());v.addView(kc,wrap());v.setOnClickListener(a->portion(m));LinearLayout.LayoutParams vp=match();vp.bottomMargin=dp(9);list.addView(v,vp);}if(n==0){TextView e=txt("Nenhum prato encontrado.",13,MUTED,true);e.setGravity(Gravity.CENTER);e.setPadding(0,dp(35),0,0);list.addView(e,match());}}
  void portion(Meal m){String[] sizes={"Pequeno · "+m.small()+" kcal","Normal · "+m.k+" kcal","Grande · "+m.large()+" kcal"};final int[] c={1};AlertDialog d=new AlertDialog.Builder(this).setTitle(m.e+"  "+m.n).setSingleChoiceItems(sizes,1,(x,w)->c[0]=w).setNegativeButton("Cancelar",null).setPositiveButton("Continuar",null).create();d.setOnShowListener(x->d.getButton(-1).setOnClickListener(v->{d.dismiss();int kcal=c[0]==0?m.small():c[0]==2?m.large():m.k;String size=c[0]==0?"Pequeno":c[0]==2?"Grande":"Normal";slot(m,kcal,size);}));d.show();}
  void slot(Meal m,int kcal,String size){String[] a={"Café da manhã","Almoço","Lanche","Jantar","Ceia"};new AlertDialog.Builder(this).setTitle("Adicionar em qual refeição?").setItems(a,(d,i)->{saveMeal(m,a[i],kcal,size);Toast.makeText(this,"Adicionado: "+m.n,Toast.LENGTH_SHORT).show();show("home");}).setNegativeButton("Cancelar",null).show();}

  View diary(){ScrollView s=scroll();LinearLayout q=page();s.addView(q);TextView k=txt("DIÁRIO ALIMENTAR",10,GREEN,true);k.setLetterSpacing(.16f);LinearLayout.LayoutParams kp=match();kp.topMargin=dp(16);q.addView(k,kp);TextView t=txt("Sua semana em números.",30,INK,true);LinearLayout.LayoutParams tp=match();tp.topMargin=dp(5);q.addView(t,tp);q.addView(txt("A média da semana vale mais que um único dia fora da meta.",12,MUTED,false),match());LinearLayout bars=row();bars.setGravity(Gravity.BOTTOM);LinearLayout.LayoutParams bp=match();bp.topMargin=dp(22);q.addView(bars,bp);Calendar c=Calendar.getInstance();c.add(Calendar.DAY_OF_YEAR,-6);int total=0;for(int i=0;i<7;i++){Date date=c.getTime();String key=new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(date);int kcal=calories(key);total+=kcal;LinearLayout one=col();one.setGravity(Gravity.CENTER_HORIZONTAL|Gravity.BOTTOM);int bh=Math.max(dp(8),Math.min(dp(70),(int)(dp(70)*(kcal/(double)Math.max(1,goal())))));View bar=new View(this);bar.setBackground(bg(kcal>goal()?RED:GREEN,8,0,0));one.addView(bar,new LinearLayout.LayoutParams(dp(22),bh));TextView lab=txt(new SimpleDateFormat("EE",new Locale("pt","BR")).format(date).substring(0,2),9,MUTED,true);LinearLayout.LayoutParams lp=wrap();lp.topMargin=dp(7);one.addView(lab,lp);bars.addView(one,new LinearLayout.LayoutParams(0,dp(105),1));c.add(Calendar.DAY_OF_YEAR,1);}LinearLayout avg=card();LinearLayout.LayoutParams ap=match();ap.topMargin=dp(14);q.addView(avg,ap);avg.addView(txt("MÉDIA DOS ÚLTIMOS 7 DIAS",10,MUTED,true),match());avg.addView(txt((total/7)+" kcal/dia",26,INK,true),match());TextView h=txt("Hoje",18,INK,true);LinearLayout.LayoutParams hp=match();hp.topMargin=dp(26);hp.bottomMargin=dp(10);q.addView(h,hp);entries(q,99);return s;}

  View progress(){ScrollView s=scroll();LinearLayout q=page();s.addView(q);TextView k=txt("PROGRESSO",10,GREEN,true);k.setLetterSpacing(.16f);LinearLayout.LayoutParams kp=match();kp.topMargin=dp(16);q.addView(k,kp);TextView t=txt("Seu corpo muda com consistência.",29,INK,true);LinearLayout.LayoutParams tp=match();tp.topMargin=dp(5);q.addView(t,tp);LinearLayout h=card();LinearLayout.LayoutParams hp=match();hp.topMargin=dp(21);q.addView(h,hp);h.addView(txt("PESO ATUAL",10,MUTED,true),match());h.addView(txt(f1(weight())+" kg",34,INK,true),match());h.addView(txt("Meta: "+f1(goalWeight())+" kg",12,GREEN,true),match());LinearLayout g=row();LinearLayout.LayoutParams gp=match();gp.topMargin=dp(10);q.addView(g,gp);g.addView(metric("◎",f1(bmi()),"IMC"),new LinearLayout.LayoutParams(0,dp(115),1));g.addView(new View(this),new LinearLayout.LayoutParams(dp(10),1));g.addView(metric("🔥",""+goal(),"Meta kcal/dia"),new LinearLayout.LayoutParams(0,dp(115),1));LinearLayout a=row();LinearLayout.LayoutParams aa=match();aa.topMargin=dp(17);q.addView(a,aa);TextView w=button("Registrar peso");w.setOnClickListener(v->weightDialog());a.addView(w,new LinearLayout.LayoutParams(0,dp(50),1));a.addView(new View(this),new LinearLayout.LayoutParams(dp(10),1));TextView e=button("Editar perfil");e.setOnClickListener(v->profileDialog());a.addView(e,new LinearLayout.LayoutParams(0,dp(50),1));LinearLayout info=card();LinearLayout.LayoutParams ip=match();ip.topMargin=dp(18);q.addView(info,ip);info.addView(txt("LEITURA DO IMC",10,MUTED,true),match());info.addView(txt(bmiClass(bmi()),19,INK,true),match());TextView note=txt("O IMC é apenas uma referência e não diferencia gordura de massa muscular. Acompanhe também sua evolução e procure orientação profissional quando necessário.",11,MUTED,false);LinearLayout.LayoutParams np=match();np.topMargin=dp(8);info.addView(note,np);return s;}
  void weightDialog(){EditText e=num(f1(weight()));FrameLayout b=new FrameLayout(this);b.setPadding(dp(20),0,dp(20),0);b.addView(e,new FrameLayout.LayoutParams(-1,-2));new AlertDialog.Builder(this).setTitle("Registrar peso atual").setView(b).setPositiveButton("Salvar",(d,x)->{try{float z=Float.parseFloat(e.getText().toString().replace(',','.'));p.edit().putFloat("weight",z).apply();show("progress");}catch(Exception ex){Toast.makeText(this,"Peso inválido",Toast.LENGTH_SHORT).show();}}).setNegativeButton("Cancelar",null).show();}
  void profileDialog(){LinearLayout f=col();f.setPadding(dp(20),0,dp(20),0);EditText w=num(f1(weight())),h=num(f2(height())),g=num(f1(goalWeight())),c=num(""+goal());w.setHint("Peso (kg)");h.setHint("Altura (m)");g.setHint("Peso-meta (kg)");c.setHint("Meta de calorias");f.addView(w);f.addView(h);f.addView(g);f.addView(c);new AlertDialog.Builder(this).setTitle("Seu perfil Balyvo").setView(f).setPositiveButton("Salvar",(d,x)->{try{p.edit().putFloat("weight",Float.parseFloat(w.getText().toString().replace(',','.'))).putFloat("height",Float.parseFloat(h.getText().toString().replace(',','.'))).putFloat("goalWeight",Float.parseFloat(g.getText().toString().replace(',','.'))).putInt("goal",Integer.parseInt(c.getText().toString().replaceAll("[^0-9]",""))).apply();show("progress");}catch(Exception ex){Toast.makeText(this,"Confira os valores",Toast.LENGTH_SHORT).show();}}).setNegativeButton("Cancelar",null).show();}

  void saveMeal(Meal m,String slot,int kcal,String size){try{JSONArray a=today();JSONObject o=new JSONObject();o.put("meal",m.n);o.put("slot",slot);o.put("kcal",kcal);o.put("size",size);a.put(o);p.edit().putString("entries_"+key(),a.toString()).apply();}catch(Exception ignored){}}
  JSONArray today(){return entries(key());}JSONArray entries(String k){try{return new JSONArray(p.getString("entries_"+k,"[]"));}catch(Exception e){return new JSONArray();}}int todayCalories(){return calories(key());}int calories(String k){int z=0;JSONArray a=entries(k);for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o!=null)z+=o.optInt("kcal");}return z;}
  void entries(LinearLayout q,int limit){JSONArray a=today();if(a.length()==0){LinearLayout e=card();e.setGravity(Gravity.CENTER);e.addView(txt("🍽",30,INK,false),wrap());e.addView(txt("Seu dia começa aqui",15,INK,true),wrap());e.addView(txt("Adicione um prato pronto e o Balyvo faz as contas.",11,MUTED,false),wrap());q.addView(e,match());return;}int start=Math.max(0,a.length()-limit);for(int i=a.length()-1;i>=start;i--){JSONObject o=a.optJSONObject(i);if(o==null)continue;LinearLayout v=row();v.setGravity(Gravity.CENTER_VERTICAL);v.setPadding(dp(14),dp(12),dp(14),dp(12));v.setBackground(bg(WHITE,16,BORDER,1));LinearLayout l=col();v.addView(l,new LinearLayout.LayoutParams(0,-2,1));l.addView(txt(o.optString("meal"),13,INK,true),match());l.addView(txt(o.optString("slot")+" · "+o.optString("size"),10,MUTED,false),match());v.addView(txt(o.optInt("kcal")+" kcal",13,GREEN,true),wrap());LinearLayout.LayoutParams vp=match();vp.bottomMargin=dp(8);q.addView(v,vp);}}

  double weight(){return p.getFloat("weight",140f);}double height(){return p.getFloat("height",1.78f);}double goalWeight(){return p.getFloat("goalWeight",105f);}int goal(){return p.getInt("goal",2400);}double bmi(){return weight()/(height()*height());}String bmiClass(double x){return x<18.5?"Abaixo do peso":x<25?"Faixa considerada adequada":x<30?"Sobrepeso":x<35?"Obesidade grau I":x<40?"Obesidade grau II":"Obesidade grau III";}String key(){return new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(new Date());}
  LinearLayout stat(String a,String b){LinearLayout x=col();x.addView(txt(a,10,MUTED,true),match());x.addView(txt(b,16,INK,true),match());return x;}LinearLayout metric(String i,String v,String l){LinearLayout x=col();x.setPadding(dp(15),dp(13),dp(15),dp(13));x.setBackground(bg(WHITE,20,BORDER,1));x.addView(txt(i,18,GREEN,true),wrap());x.addView(txt(v,18,INK,true),match());x.addView(txt(l,10,MUTED,false),match());return x;}TextView button(String s){TextView b=txt(s,12,WHITE,true);b.setGravity(Gravity.CENTER);b.setBackground(bg(INK,16,0,0));return b;}EditText num(String v){EditText e=new EditText(this);e.setText(v);e.setSelectAllOnFocus(true);e.setInputType(android.text.InputType.TYPE_CLASS_NUMBER|android.text.InputType.TYPE_NUMBER_FLAG_DECIMAL);return e;}
  ScrollView scroll(){ScrollView s=new ScrollView(this);s.setFillViewport(true);s.setVerticalScrollBarEnabled(false);s.setBackgroundColor(CANVAS);return s;}LinearLayout page(){LinearLayout q=col();q.setPadding(dp(20),dp(8),dp(20),dp(34));return q;}LinearLayout card(){LinearLayout x=col();x.setPadding(dp(18),dp(18),dp(18),dp(18));x.setBackground(bg(WHITE,23,BORDER,1));return x;}LinearLayout row(){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.HORIZONTAL);return x;}LinearLayout col(){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);return x;}TextView txt(String s,float z,int c,boolean b){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);t.setTypeface(Typeface.create("sans",b?Typeface.BOLD:Typeface.NORMAL));return t;}GradientDrawable bg(int c,int r,int sc,int sw){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));if(sw>0)g.setStroke(dp(sw),sc);return g;}LinearLayout.LayoutParams wrap(){return new LinearLayout.LayoutParams(-2,-2);}LinearLayout.LayoutParams match(){return new LinearLayout.LayoutParams(-1,-2);}int dp(int x){return Math.round(x*getResources().getDisplayMetrics().density);}String f1(double x){return String.format(new Locale("pt","BR"),"%.1f",x);}String f2(double x){return String.format(new Locale("pt","BR"),"%.2f",x);}

  void seed(){add("Arroz, feijão e 2 ovos cozidos","🥚","Brasileiro","Porção caseira padrão",410);add("Arroz, feijão e 2 ovos fritos","🍳","Brasileiro","Ovos com pouco óleo",470);add("Arroz, feijão e omelete 2 ovos","🍳","Ovos","Omelete simples",450);add("Arroz, feijão e omelete 3 ovos","🍳","Ovos","Mais proteína e saciedade",530);add("Arroz, feijão e bife","🥩","Carnes","Bife bovino grelhado",580);add("Arroz, feijão e carne moída","🥩","Carnes","Carne moída refogada",560);add("Arroz, feijão e músculo moído","🥩","Carnes","Músculo moído com temperos",550);add("Arroz, feijão e carne de panela","🍲","Carnes","Carne cozida com molho caseiro",590);add("Arroz, feijão e frango grelhado","🍗","Frango","Peito de frango grelhado",520);add("Arroz, feijão e frango em cubos","🍗","Frango","Frango em cubos refogado",540);add("Arroz, feijão e costela suína","🍖","Carnes","Costela suína assada",690);add("Arroz, feijão e linguiça","🌭","Carnes","Linguiça grelhada",650);add("Macarrão com carne moída","🍝","Massas","Molho de tomate natural e carne moída",680);add("Macarrão com frango em cubos","🍝","Massas","Frango em cubos e molho caseiro",640);add("Macarrão alho e óleo","🍝","Massas","Porção tradicional",540);add("Macarrão com ovos","🍝","Massas","Macarrão com 2 ovos",560);add("Lasanha à bolonhesa","🧀","Massas","Porção média",650);add("Frango, batata-doce e salada","🍗","Frango","Refeição simples e saciante",490);add("Carne, batata-doce e salada","🥩","Carnes","Carne bovina com batata-doce",550);add("Omelete 3 ovos e salada","🍳","Ovos","Omelete com salada fresca",350);add("Omelete, arroz e salada","🍳","Ovos","Omelete 3 ovos com arroz",470);add("Omelete, arroz, feijão e salada","🍳","Ovos","Prato completo",540);add("Churrasco com salada","🔥","Churrasco","Seleção de carnes e salada",660);add("Churrasco, arroz e salada","🔥","Churrasco","Carnes, arroz e salada",810);add("Churrasco, arroz, feijão e salada","🔥","Churrasco","Prato completo de churrasco",900);add("Churrasco, pão e salada","🔥","Churrasco","Carnes, pão e salada",850);add("Arroz, feijão e tilápia","🐟","Peixes","Filé de tilápia grelhado",500);add("Peixe grelhado, arroz e salada","🐟","Peixes","Peixe branco grelhado",480);add("Salmão, arroz e salada","🐟","Peixes","Salmão grelhado",610);add("Sardinha, arroz e feijão","🐟","Peixes","Sardinha com prato brasileiro",560);add("Peixe assado, batata e salada","🐟","Peixes","Peixe assado com batata",530);add("Moqueca de peixe com arroz","🥘","Peixes","Moqueca tradicional",720);add("Camarão, arroz e salada","🦐","Frutos do mar","Camarões salteados",540);add("Macarrão com camarão","🦐","Frutos do mar","Massa, molho e camarões",680);add("Risoto de camarão","🦐","Frutos do mar","Porção média de risoto",720);add("Lula, arroz e salada","🦑","Frutos do mar","Lula grelhada",520);add("Frutos do mar com arroz","🦐","Frutos do mar","Mix de frutos do mar",620);}
  void add(String n,String e,String c,String d,int k){meals.add(new Meal(n,e,c,d,k));}static class Meal{String n,e,c,d;int k;Meal(String a,String b,String c1,String d1,int x){n=a;e=b;c=c1;d=d1;k=x;}int small(){return Math.round(k*.75f);}int large(){return Math.round(k*1.35f);}}
}
