package app.balyvo.mobile;

import android.app.*;
import android.os.*;
import android.graphics.*;
import android.content.*;
import android.content.res.ColorStateList;
import android.text.*;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.text.*;
import java.util.*;

public class MainActivityV3 extends MainActivityV2 {
  static final int NIGHT=Color.parseColor("#050807"), SURFACE=Color.parseColor("#0C1210"), SURFACE2=Color.parseColor("#121A17"),
      NEON=Color.parseColor("#BDFD44"), TEXT=Color.parseColor("#F5F8F2"), SOFT=Color.parseColor("#A2ADA6"),
      LINE=Color.parseColor("#25302B"), CYAN=Color.parseColor("#67E8F9"), AMBER=Color.parseColor("#F4C95D"), ROSE=Color.parseColor("#FF758F");

  @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(NIGHT);getWindow().setNavigationBarColor(NIGHT);getWindow().getDecorView().setSystemUiVisibility(0);}

  @Override void splash(){
    FrameLayout f=new FrameLayout(this);f.setBackgroundColor(NIGHT);LinearLayout c=col();c.setGravity(Gravity.CENTER);c.setPadding(dp(34),0,dp(34),0);f.addView(c,new FrameLayout.LayoutParams(-1,-1));
    BrandMarkView mark=new BrandMarkView(this);c.addView(mark,new LinearLayout.LayoutParams(dp(92),dp(92)));
    TextView n=txt("Balyvo",36,TEXT,true);n.setLetterSpacing(-0.02f);LinearLayout.LayoutParams np=wrap();np.topMargin=dp(18);c.addView(n,np);
    TextView s=txt("NUTRIÇÃO PARA A VIDA REAL",10,NEON,true);s.setLetterSpacing(.18f);LinearLayout.LayoutParams sp=wrap();sp.topMargin=dp(7);c.addView(s,sp);
    TextView sub=txt("Sua comida. Seu controle. Seu progresso.",12,SOFT,false);LinearLayout.LayoutParams sb=wrap();sb.topMargin=dp(20);c.addView(sub,sb);
    setContentView(f);f.setAlpha(0f);f.animate().alpha(1f).setDuration(420).start();new Handler(Looper.getMainLooper()).postDelayed(this::shell,1350);
  }

  @Override void shell(){LinearLayout r=col();r.setBackgroundColor(NIGHT);body=new FrameLayout(this);r.addView(body,new LinearLayout.LayoutParams(-1,0,1));nav=row();nav.setPadding(dp(8),dp(5),dp(8),dp(8));nav.setGravity(Gravity.CENTER);nav.setBackgroundColor(SURFACE);r.addView(nav,new LinearLayout.LayoutParams(-1,dp(72)));setContentView(r);show("home");}
  @Override void nav(){nav.removeAllViews();navItem("⌂","Hoje","home");navItem("＋","Pratos","meals");navItem("≡","Diário","diary");navItem("↗","Evolução","progress");}
  @Override void navItem(String i,String l,String k){LinearLayout v=col();v.setGravity(Gravity.CENTER);boolean a=k.equals(tab);TextView icon=txt(i,21,a?NIGHT:SOFT,true);icon.setGravity(Gravity.CENTER);if(a)icon.setBackground(bg(NEON,14,0,0));v.addView(icon,new LinearLayout.LayoutParams(dp(36),dp(32)));TextView lab=txt(l,9,a?NEON:SOFT,true);LinearLayout.LayoutParams lp=wrap();lp.topMargin=dp(3);v.addView(lab,lp);v.setOnClickListener(x->show(k));nav.addView(v,new LinearLayout.LayoutParams(0,-1,1));}

  @Override View home(){
    ScrollView s=scroll();LinearLayout q=page();s.addView(q);
    LinearLayout head=row();head.setGravity(Gravity.CENTER_VERTICAL);BrandMarkView mark=new BrandMarkView(this);head.addView(mark,new LinearLayout.LayoutParams(dp(44),dp(44)));LinearLayout brand=col();LinearLayout.LayoutParams blp=new LinearLayout.LayoutParams(0,-2,1);blp.leftMargin=dp(10);head.addView(brand,blp);brand.addView(txt("Balyvo",20,TEXT,true),match());brand.addView(txt("HOJE · "+new SimpleDateFormat("dd MMM",new Locale("pt","BR")).format(new Date()).toUpperCase(new Locale("pt","BR")),9,NEON,true),match());head.addView(chip("🔥 "+streak()+" dias"),wrap());q.addView(head,match());
    TextView eye=txt("SEU DIA, NO CONTROLE",10,NEON,true);eye.setLetterSpacing(.16f);LinearLayout.LayoutParams ep=match();ep.topMargin=dp(30);q.addView(eye,ep);TextView title=txt("Coma de verdade.\nEvolua todos os dias.",31,TEXT,true);LinearLayout.LayoutParams tp=match();tp.topMargin=dp(5);q.addView(title,tp);
    int used=todayCalories(),g=goal(),rem=Math.max(0,g-used);LinearLayout hero=row();hero.setGravity(Gravity.CENTER_VERTICAL);hero.setPadding(dp(16),dp(18),dp(16),dp(18));hero.setBackground(bg(SURFACE,24,LINE,1));LinearLayout.LayoutParams hp=match();hp.topMargin=dp(20);q.addView(hero,hp);hero.addView(new CalorieRing(this,used,g),new LinearLayout.LayoutParams(dp(142),dp(142)));LinearLayout hs=col();LinearLayout.LayoutParams hsp=new LinearLayout.LayoutParams(0,-2,1);hsp.leftMargin=dp(16);hero.addView(hs,hsp);hs.addView(txt("CALORIAS RESTANTES",9,SOFT,true),match());hs.addView(txt(""+rem,31,TEXT,true),match());hs.addView(txt("de "+g+" kcal",11,SOFT,false),match());LinearLayout.LayoutParams gap=match();gap.topMargin=dp(15);hs.addView(txt("Consumidas  "+used+" kcal",11,NEON,true),gap);hs.addView(txt(progressLabel(used,g),10,SOFT,false),match());
    int[] macros=macroEstimate();TextView mt=txt("Macros de hoje",18,TEXT,true);LinearLayout.LayoutParams mtp=match();mtp.topMargin=dp(25);q.addView(mt,mtp);q.addView(txt("estimativa pela composição dos pratos registrados",9,SOFT,false),match());LinearLayout mac=row();LinearLayout.LayoutParams mp=match();mp.topMargin=dp(10);q.addView(mac,mp);mac.addView(macroCard("PROTEÍNA",macros[0]+" g",CYAN),new LinearLayout.LayoutParams(0,dp(96),1));spacer(mac,8);mac.addView(macroCard("CARBO",macros[1]+" g",NEON),new LinearLayout.LayoutParams(0,dp(96),1));spacer(mac,8);mac.addView(macroCard("GORDURA",macros[2]+" g",AMBER),new LinearLayout.LayoutParams(0,dp(96),1));
    LinearLayout quick=row();LinearLayout.LayoutParams qp=match();qp.topMargin=dp(16);q.addView(quick,qp);TextView add=actionCard("＋","Adicionar refeição","200 pratos brasileiros");add.setOnClickListener(v->show("meals"));quick.addView(add,new LinearLayout.LayoutParams(0,dp(92),1));spacer(quick,10);TextView repeat=actionCard("↻","Repetir última","1 toque para registrar");repeat.setOnClickListener(v->repeatLast());quick.addView(repeat,new LinearLayout.LayoutParams(0,dp(92),1));
    LinearLayout water=card();LinearLayout.LayoutParams wp=match();wp.topMargin=dp(16);q.addView(water,wp);LinearLayout wh=row();wh.setGravity(Gravity.CENTER_VERTICAL);LinearLayout wl=col();wh.addView(wl,new LinearLayout.LayoutParams(0,-2,1));wl.addView(txt("HIDRATAÇÃO",9,CYAN,true),match());int ml=waterMl();wl.addView(txt((ml<1000?ml+" ml":String.format(new Locale("pt","BR"),"%.1f L",ml/1000f))+"  /  3,0 L",18,TEXT,true),match());TextView wbtt=chip("＋ 250 ml");wbtt.setOnClickListener(v->{addWater(250);show("home");});wh.addView(wbtt,wrap());water.addView(wh,match());ProgressBar wb=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);wb.setMax(3000);wb.setProgress(Math.min(ml,3000));wb.setProgressTintList(ColorStateList.valueOf(CYAN));wb.setProgressBackgroundTintList(ColorStateList.valueOf(LINE));LinearLayout.LayoutParams wbp=new LinearLayout.LayoutParams(-1,dp(7));wbp.topMargin=dp(12);water.addView(wb,wbp);
    Meal rec=recommendation(rem);if(rec!=null){TextView rt=txt("Sugestão inteligente",18,TEXT,true);LinearLayout.LayoutParams rtp=match();rtp.topMargin=dp(25);q.addView(rt,rtp);LinearLayout rc=row();rc.setGravity(Gravity.CENTER_VERTICAL);rc.setPadding(dp(16),dp(15),dp(16),dp(15));rc.setBackground(bg(SURFACE2,22,LINE,1));TextView em=txt(rec.e,30,TEXT,false);em.setGravity(Gravity.CENTER);em.setBackground(bg(NIGHT,16,LINE,1));rc.addView(em,new LinearLayout.LayoutParams(dp(58),dp(58)));LinearLayout ri=col();LinearLayout.LayoutParams rip=new LinearLayout.LayoutParams(0,-2,1);rip.leftMargin=dp(12);rc.addView(ri,rip);ri.addView(txt(rec.n,13,TEXT,true),match());ri.addView(txt("Cabe no seu saldo · "+rec.k+" kcal",10,NEON,true),match());rc.addView(txt("›",28,NEON,false),wrap());rc.setOnClickListener(v->portion(rec));LinearLayout.LayoutParams rcp=match();rcp.topMargin=dp(10);q.addView(rc,rcp);}
    TextView lt=txt("Últimas refeições",18,TEXT,true);LinearLayout.LayoutParams ltp=match();ltp.topMargin=dp(25);ltp.bottomMargin=dp(10);q.addView(lt,ltp);entries(q,3);TextView note=txt("Calorias e macros são estimativas de referência. O Balyvo apoia o acompanhamento e não substitui avaliação profissional.",9,SOFT,false);note.setGravity(Gravity.CENTER);LinearLayout.LayoutParams np=match();np.topMargin=dp(18);np.bottomMargin=dp(18);q.addView(note,np);return s;
  }

  @Override View mealScreen(){
    LinearLayout root=col();root.setBackgroundColor(NIGHT);LinearLayout top=page();top.setPadding(dp(20),dp(16),dp(20),dp(4));TextView k=txt("BIBLIOTECA BRASILEIRA",9,NEON,true);k.setLetterSpacing(.16f);top.addView(k,match());TextView t=txt("O que entrou no prato?",29,TEXT,true);LinearLayout.LayoutParams tp=match();tp.topMargin=dp(4);top.addView(t,tp);top.addView(txt("Busque, escolha a porção e registre em segundos.",11,SOFT,false),match());EditText search=new EditText(this);search.setHint("Buscar arroz, frango, macarrão...");search.setSingleLine();search.setTextColor(TEXT);search.setHintTextColor(SOFT);search.setTextSize(13);search.setPadding(dp(15),dp(11),dp(15),dp(11));search.setBackground(bg(SURFACE2,18,LINE,1));LinearLayout.LayoutParams sep=match();sep.topMargin=dp(14);top.addView(search,sep);root.addView(top,match());
    HorizontalScrollView hs=new HorizontalScrollView(this);hs.setHorizontalScrollBarEnabled(false);LinearLayout ch=row();ch.setPadding(dp(20),dp(7),dp(20),dp(7));hs.addView(ch,wrap());String[] cats={"Todos","Brasileiro","Massas","Ovos","Carnes","Frango","Peixes","Frutos do mar","Churrasco"};for(String c:cats){boolean on=c.equals(cat);TextView z=txt(c,10,on?NIGHT:SOFT,true);z.setGravity(Gravity.CENTER);z.setPadding(dp(14),dp(9),dp(14),dp(9));z.setBackground(bg(on?NEON:SURFACE,99,on?NEON:LINE,1));LinearLayout.LayoutParams zp=wrap();zp.rightMargin=dp(8);ch.addView(z,zp);z.setOnClickListener(v->{cat=((TextView)v).getText().toString();show("meals");});}root.addView(hs,new LinearLayout.LayoutParams(-1,dp(56)));
    ScrollView sc=scroll();LinearLayout list=col();list.setPadding(dp(20),dp(3),dp(20),dp(25));sc.addView(list);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));Runnable r=()->renderMeals(list,search.getText().toString());search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int b,int c){}public void onTextChanged(CharSequence s,int a,int b,int c){r.run();}public void afterTextChanged(Editable e){}});renderMeals(list,"");return root;
  }

  @Override void renderMeals(LinearLayout list,String query){list.removeAllViews();String x=query.toLowerCase(Locale.ROOT).trim();int n=0;for(Meal m:meals){if(!cat.equals("Todos")&&!cat.equals(m.c))continue;if(!x.isEmpty()&&!m.n.toLowerCase(Locale.ROOT).contains(x))continue;n++;LinearLayout v=row();v.setGravity(Gravity.CENTER_VERTICAL);v.setPadding(dp(13),dp(13),dp(13),dp(13));v.setBackground(bg(SURFACE,20,LINE,1));TextView em=txt(m.e,26,TEXT,false);em.setGravity(Gravity.CENTER);em.setBackground(bg(SURFACE2,15,LINE,1));v.addView(em,new LinearLayout.LayoutParams(dp(54),dp(54)));LinearLayout inf=col();LinearLayout.LayoutParams ip=new LinearLayout.LayoutParams(0,-2,1);ip.leftMargin=dp(12);v.addView(inf,ip);inf.addView(txt(m.n,13,TEXT,true),match());inf.addView(txt(m.c+" · "+m.d,9,SOFT,false),match());LinearLayout kc=col();kc.setGravity(Gravity.RIGHT);kc.addView(txt(""+m.k,16,NEON,true),wrap());kc.addView(txt("kcal",9,SOFT,true),wrap());v.addView(kc,wrap());v.setOnClickListener(a->portion(m));LinearLayout.LayoutParams vp=match();vp.bottomMargin=dp(9);list.addView(v,vp);}if(n==0){TextView e=txt("Nenhum prato encontrado.",12,SOFT,true);e.setGravity(Gravity.CENTER);e.setPadding(0,dp(35),0,0);list.addView(e,match());}}

  @Override View diary(){ScrollView s=scroll();LinearLayout q=page();s.addView(q);TextView k=txt("DIÁRIO",9,NEON,true);k.setLetterSpacing(.16f);LinearLayout.LayoutParams kp=match();kp.topMargin=dp(12);q.addView(k,kp);TextView t=txt("Sua semana, sem achismo.",29,TEXT,true);LinearLayout.LayoutParams tp=match();tp.topMargin=dp(4);q.addView(t,tp);q.addView(txt("Veja tendência, média e consistência — não só um dia isolado.",11,SOFT,false),match());LinearLayout chart=card();LinearLayout.LayoutParams cp=match();cp.topMargin=dp(20);q.addView(chart,cp);LinearLayout bars=row();bars.setGravity(Gravity.BOTTOM);chart.addView(bars,new LinearLayout.LayoutParams(-1,dp(128)));Calendar c=Calendar.getInstance();c.add(Calendar.DAY_OF_YEAR,-6);int total=0,active=0;for(int i=0;i<7;i++){Date date=c.getTime();String kk=new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(date);int kcal=calories(kk);total+=kcal;if(kcal>0)active++;LinearLayout one=col();one.setGravity(Gravity.CENTER_HORIZONTAL|Gravity.BOTTOM);int bh=Math.max(dp(6),Math.min(dp(82),(int)(dp(82)*(kcal/(double)Math.max(1,goal())))));View bar=new View(this);bar.setBackground(bg(kcal>goal()?ROSE:(kcal>0?NEON:LINE),8,0,0));one.addView(bar,new LinearLayout.LayoutParams(dp(22),bh));String day=new SimpleDateFormat("EE",new Locale("pt","BR")).format(date).substring(0,2).toUpperCase(new Locale("pt","BR"));TextView lab=txt(day,8,SOFT,true);LinearLayout.LayoutParams lp=wrap();lp.topMargin=dp(7);one.addView(lab,lp);bars.addView(one,new LinearLayout.LayoutParams(0,dp(116),1));c.add(Calendar.DAY_OF_YEAR,1);}LinearLayout stats=row();LinearLayout.LayoutParams stp=match();stp.topMargin=dp(10);chart.addView(stats,stp);stats.addView(darkStat("MÉDIA",(total/7)+" kcal"),new LinearLayout.LayoutParams(0,dp(60),1));spacer(stats,8);stats.addView(darkStat("DIAS ATIVOS",active+"/7"),new LinearLayout.LayoutParams(0,dp(60),1));TextView h=txt("Hoje",18,TEXT,true);LinearLayout.LayoutParams hp=match();hp.topMargin=dp(24);hp.bottomMargin=dp(10);q.addView(h,hp);entries(q,99);return s;}

  @Override View progress(){ScrollView s=scroll();LinearLayout q=page();s.addView(q);TextView k=txt("EVOLUÇÃO",9,NEON,true);k.setLetterSpacing(.16f);LinearLayout.LayoutParams kp=match();kp.topMargin=dp(12);q.addView(k,kp);TextView t=txt("Consistência deixa rastros.",29,TEXT,true);LinearLayout.LayoutParams tp=match();tp.topMargin=dp(4);q.addView(t,tp);q.addView(txt("Peso, IMC, meta e aderência reunidos em um painel.",11,SOFT,false),match());LinearLayout hero=card();LinearLayout.LayoutParams hp=match();hp.topMargin=dp(20);q.addView(hero,hp);LinearLayout hh=row();hh.setGravity(Gravity.CENTER_VERTICAL);LinearLayout wl=col();hh.addView(wl,new LinearLayout.LayoutParams(0,-2,1));wl.addView(txt("PESO ATUAL",9,SOFT,true),match());wl.addView(txt(f1(weight())+" kg",34,TEXT,true),match());wl.addView(txt("Meta  "+f1(goalWeight())+" kg",11,NEON,true),match());hh.addView(chip("Faltam "+f1(Math.max(0,weight()-goalWeight()))+" kg"),wrap());hero.addView(hh,match());LinearLayout g=row();LinearLayout.LayoutParams gp=match();gp.topMargin=dp(12);q.addView(g,gp);g.addView(metric("◎",f1(bmi()),"IMC"),new LinearLayout.LayoutParams(0,dp(112),1));spacer(g,10);g.addView(metric("🔥",""+goal(),"Meta kcal"),new LinearLayout.LayoutParams(0,dp(112),1));LinearLayout g2=row();LinearLayout.LayoutParams g2p=match();g2p.topMargin=dp(10);q.addView(g2,g2p);g2.addView(metric("⚡",""+streak(),"Dias ativos"),new LinearLayout.LayoutParams(0,dp(112),1));spacer(g2,10);g2.addView(metric("💧",String.format(new Locale("pt","BR"),"%.1f",waterMl()/1000f)+" L","Água hoje"),new LinearLayout.LayoutParams(0,dp(112),1));LinearLayout a=row();LinearLayout.LayoutParams aa=match();aa.topMargin=dp(16);q.addView(a,aa);TextView w=button("Registrar peso");w.setOnClickListener(v->weightDialog());a.addView(w,new LinearLayout.LayoutParams(0,dp(50),1));spacer(a,10);TextView e=button("Editar perfil");e.setOnClickListener(v->profileDialog());a.addView(e,new LinearLayout.LayoutParams(0,dp(50),1));LinearLayout info=card();LinearLayout.LayoutParams ip=match();ip.topMargin=dp(16);q.addView(info,ip);info.addView(txt("LEITURA DO IMC",9,SOFT,true),match());info.addView(txt(bmiClass(bmi()),18,TEXT,true),match());TextView note=txt("IMC é apenas uma referência populacional. Ele não diferencia gordura de massa muscular e não substitui avaliação profissional.",10,SOFT,false);LinearLayout.LayoutParams np=match();np.topMargin=dp(7);info.addView(note,np);return s;}

  @Override void entries(LinearLayout q,int limit){JSONArray a=today();if(a.length()==0){LinearLayout e=card();e.setGravity(Gravity.CENTER);e.addView(txt("◌",32,NEON,false),wrap());e.addView(txt("Seu dia começa aqui",14,TEXT,true),wrap());e.addView(txt("Registre a primeira refeição e o painel ganha vida.",10,SOFT,false),wrap());q.addView(e,match());return;}int start=Math.max(0,a.length()-limit);for(int i=a.length()-1;i>=start;i--){JSONObject o=a.optJSONObject(i);if(o==null)continue;LinearLayout v=row();v.setGravity(Gravity.CENTER_VERTICAL);v.setPadding(dp(14),dp(12),dp(14),dp(12));v.setBackground(bg(SURFACE,17,LINE,1));v.addView(txt("●",12,NEON,true),new LinearLayout.LayoutParams(dp(24),dp(24)));LinearLayout l=col();LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,-2,1);lp.leftMargin=dp(8);v.addView(l,lp);l.addView(txt(o.optString("meal"),12,TEXT,true),match());l.addView(txt(o.optString("slot")+" · "+o.optString("size"),9,SOFT,false),match());v.addView(txt(o.optInt("kcal")+" kcal",12,NEON,true),wrap());LinearLayout.LayoutParams vp=match();vp.bottomMargin=dp(8);q.addView(v,vp);}}

  @Override ScrollView scroll(){ScrollView s=new ScrollView(this);s.setFillViewport(true);s.setVerticalScrollBarEnabled(false);s.setBackgroundColor(NIGHT);return s;}
  @Override LinearLayout page(){LinearLayout q=col();q.setPadding(dp(20),dp(10),dp(20),dp(32));return q;}
  @Override LinearLayout card(){LinearLayout x=col();x.setPadding(dp(17),dp(17),dp(17),dp(17));x.setBackground(bg(SURFACE,22,LINE,1));return x;}
  @Override LinearLayout stat(String a,String b){return darkStat(a,b);}
  @Override LinearLayout metric(String i,String v,String l){LinearLayout x=col();x.setPadding(dp(15),dp(13),dp(15),dp(13));x.setBackground(bg(SURFACE,20,LINE,1));x.addView(txt(i,18,NEON,true),wrap());x.addView(txt(v,18,TEXT,true),match());x.addView(txt(l,9,SOFT,false),match());return x;}
  @Override TextView button(String s){TextView b=txt(s,11,NIGHT,true);b.setGravity(Gravity.CENTER);b.setBackground(bg(NEON,16,0,0));return b;}

  LinearLayout darkStat(String a,String b){LinearLayout x=col();x.setPadding(dp(11),dp(8),dp(11),dp(8));x.setBackground(bg(SURFACE2,16,LINE,1));x.addView(txt(a,8,SOFT,true),match());x.addView(txt(b,14,TEXT,true),match());return x;}
  LinearLayout macroCard(String label,String value,int accent){LinearLayout x=col();x.setPadding(dp(12),dp(12),dp(12),dp(12));x.setBackground(bg(SURFACE,18,LINE,1));x.addView(txt("●",10,accent,true),wrap());x.addView(txt(value,17,TEXT,true),match());x.addView(txt(label,8,SOFT,true),match());return x;}
  TextView actionCard(String icon,String title,String sub){TextView t=txt(icon+"   "+title+"\n     "+sub,11,TEXT,true);t.setGravity(Gravity.CENTER_VERTICAL);t.setPadding(dp(13),dp(11),dp(13),dp(11));t.setLineSpacing(dp(3),1f);t.setBackground(bg(SURFACE,20,LINE,1));return t;}
  TextView chip(String s){TextView t=txt(s,9,NIGHT,true);t.setGravity(Gravity.CENTER);t.setPadding(dp(10),dp(7),dp(10),dp(7));t.setBackground(bg(NEON,99,0,0));return t;}
  void spacer(LinearLayout r,int d){r.addView(new View(this),new LinearLayout.LayoutParams(dp(d),1));}

  String progressLabel(int used,int goal){if(used==0)return "Comece registrando sua primeira refeição";double z=used/(double)Math.max(1,goal);if(z<.55)return "Bom espaço para o restante do dia";if(z<.90)return "Você está avançando bem na meta";if(z<=1.05)return "Faixa próxima da sua meta diária";return "Meta ultrapassada — olhe a média semanal";}
  int streak(){Calendar c=Calendar.getInstance();int n=0;for(int i=0;i<7;i++){String k=new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(c.getTime());if(calories(k)>0)n++;c.add(Calendar.DAY_OF_YEAR,-1);}return n;}
  int waterMl(){return p.getInt("water_"+key(),0);}void addWater(int ml){p.edit().putInt("water_"+key(),Math.min(10000,waterMl()+ml)).apply();}
  void repeatLast(){JSONArray a=today();if(a.length()==0){Toast.makeText(this,"Registre uma refeição primeiro.",Toast.LENGTH_SHORT).show();show("meals");return;}JSONObject last=a.optJSONObject(a.length()-1);if(last==null)return;try{JSONArray b=today();b.put(new JSONObject(last.toString()));p.edit().putString("entries_"+key(),b.toString()).apply();Toast.makeText(this,"Última refeição repetida.",Toast.LENGTH_SHORT).show();show("home");}catch(Exception ignored){}}
  Meal recommendation(int remaining){if(remaining<180)return null;int cap=Math.min(remaining,750);Meal best=null;for(Meal m:meals){if(m.k<=cap&&m.k>=220&&(best==null||m.k>best.k))best=m;}return best;}
  int[] macroEstimate(){int protein=0,carbs=0,fat=0;JSONArray a=today();for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o==null)continue;int kcal=o.optInt("kcal");String n=o.optString("meal").toLowerCase(Locale.ROOT);double pp=.25,cp=.45,fp=.30;if(n.contains("frango")||n.contains("peixe")||n.contains("tilápia")||n.contains("atum")||n.contains("carne")||n.contains("bife")||n.contains("ovo")){pp=.32;cp=.38;fp=.30;}if(n.contains("macarr")||n.contains("lasanha")||n.contains("arroz")||n.contains("cuscuz")||n.contains("tapioca")){cp=.48;pp=.24;fp=.28;}protein+=(int)Math.round((kcal*pp)/4.0);carbs+=(int)Math.round((kcal*cp)/4.0);fat+=(int)Math.round((kcal*fp)/9.0);}return new int[]{protein,carbs,fat};}

  class CalorieRing extends View{Paint track=new Paint(Paint.ANTI_ALIAS_FLAG),arc=new Paint(Paint.ANTI_ALIAS_FLAG),big=new Paint(Paint.ANTI_ALIAS_FLAG),small=new Paint(Paint.ANTI_ALIAS_FLAG);int used,goal;CalorieRing(Context c,int u,int g){super(c);used=u;goal=Math.max(1,g);track.setStyle(Paint.Style.STROKE);track.setStrokeWidth(dp(11));track.setStrokeCap(Paint.Cap.ROUND);track.setColor(LINE);arc.setStyle(Paint.Style.STROKE);arc.setStrokeWidth(dp(11));arc.setStrokeCap(Paint.Cap.ROUND);arc.setColor(NEON);big.setColor(TEXT);big.setTextAlign(Paint.Align.CENTER);big.setTypeface(Typeface.create("sans",Typeface.BOLD));big.setTextSize(dp(25));small.setColor(SOFT);small.setTextAlign(Paint.Align.CENTER);small.setTypeface(Typeface.create("sans",Typeface.BOLD));small.setTextSize(dp(9));}@Override protected void onDraw(Canvas c){super.onDraw(c);float pad=dp(15),w=getWidth(),h=getHeight();RectF r=new RectF(pad,pad,w-pad,h-pad);c.drawArc(r,-90,360,false,track);c.drawArc(r,-90,(float)Math.min(360,360*(used/(double)goal)),false,arc);c.drawText(""+used,w/2,h/2+dp(4),big);c.drawText("KCAL",w/2,h/2+dp(22),small);}}
  class BrandMarkView extends View{Paint box=new Paint(Paint.ANTI_ALIAS_FLAG),stroke=new Paint(Paint.ANTI_ALIAS_FLAG),dot=new Paint(Paint.ANTI_ALIAS_FLAG);BrandMarkView(Context c){super(c);box.setColor(SURFACE2);stroke.setColor(NEON);stroke.setStyle(Paint.Style.STROKE);stroke.setStrokeCap(Paint.Cap.ROUND);stroke.setStrokeJoin(Paint.Join.ROUND);dot.setColor(NEON);}@Override protected void onDraw(Canvas c){super.onDraw(c);float w=getWidth(),h=getHeight(),p=Math.max(3,w*.07f);c.drawRoundRect(new RectF(p,p,w-p,h-p),w*.26f,w*.26f,box);stroke.setStrokeWidth(Math.max(5,w*.095f));float x=w*.32f;c.drawLine(x,h*.24f,x,h*.76f,stroke);c.drawArc(new RectF(w*.26f,h*.20f,w*.72f,h*.53f),-92,190,false,stroke);c.drawArc(new RectF(w*.26f,h*.46f,w*.78f,h*.79f),-92,190,false,stroke);c.drawCircle(w*.74f,h*.25f,Math.max(2,w*.035f),dot);}}
}
